services:
  web:
    build: .
    volumes:
      - newthing:/var/lib/DB_data
    ports:
      - "10001:5001"
    depends_on:
      database:
        condition: service_healthy
#  dbhandle:
#    build:
#      dockerfile: docker_dbhandle
#      context: .


  database:
    image: postgres:latest
    volumes:
      - newthing:/var/lib/DB_data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wolverine_overflow -U username"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
      #PGDATA=/var/lib/DB_data



volumes:
  newthing: