#!/bin/bash
FROM python:latest
WORKDIR /code
#ENV FLASK_RUN_HOST=0.0.0.0
#RUN apk add --no-cache gcc musl-dev linux-headers

#changed the copy recently.
COPY . . 
RUN pip install "psycopg2"
EXPOSE 10001
ENTRYPOINT ["tail", "-f", "/dev/null"]
#flask run